name: commitlint
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  commitlint:
    permissions:
      contents: read
      actions: read
    uses: cffnpwr/actions/.github/workflows/commitlint.yaml@fc0611aef262e7adbffe088d606d837bb36f4a49 # main
