name: commitlint
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  commitlint:
    permissions:
      contents: read
      actions: read
    uses: cffnpwr/actions/.github/workflows/commitlint.yaml@680e0f250b000643aafde886f3caa6603c9c8335 # main
