name: commitlint
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  commitlint:
    permissions:
      contents: read
      actions: read
    uses: cffnpwr/actions/.github/workflows/commitlint.yaml@aab8aa8f1ea7bb31a7bd84552b85f2e44bf86cdb # main
