name: GitHub Actions Lint
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  github-actions-lint:
    permissions:
      contents: read
    uses: cffnpwr/actions/.github/workflows/github-actions-lint.yaml@57d9c1cfce9d56f399a0dc0b299ed626e17a9c95 # main
