name: GitHub Actions Lint
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  github-actions-lint:
    permissions:
      contents: read
    uses: cffnpwr/actions/.github/workflows/github-actions-lint.yaml@7d1f5eb9b4337c5e644e44ee0868a937c7fefeef # main
