name: GitHub Actions Lint
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  github-actions-lint:
    permissions:
      contents: read
    uses: cffnpwr/actions/.github/workflows/github-actions-lint.yaml@f3332ff4124e0e2eb8acb10d8cd930694814c216 # main
