name: Semantic PR title
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions: {}

jobs:
  semantic-pr-title:
    permissions:
      pull-requests: read
    uses: cffnpwr/actions/.github/workflows/semantic-pr-title.yaml@fc0611aef262e7adbffe088d606d837bb36f4a49 # main
