name: Semantic PR title
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions: {}

jobs:
  semantic-pr-title:
    permissions:
      pull-requests: read
    uses: cffnpwr/actions/.github/workflows/semantic-pr-title.yaml@cc44c5825ca2ac142ee869f301526b777cdccedd # main
