name: Semantic PR title
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions: {}

jobs:
  semantic-pr-title:
    permissions:
      pull-requests: read
    uses: cffnpwr/actions/.github/workflows/semantic-pr-title.yaml@c80893822eee82c32d5ab76014ed5b35ee61fed4 # main
