name: Status check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

jobs:
  status-check:
    permissions:
      contents: read
      actions: read
      pull-requests: read
      checks: read
      statuses: read
    uses: cffnpwr/actions/.github/workflows/status-check.yaml@ef7120284c6d7078936b92d94cc2ba36606c44f9 # main
