name: Status check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

jobs:
  status-check:
    permissions:
      contents: read
      actions: read
      pull-requests: read
      checks: read
      statuses: read
    uses: cffnpwr/actions/.github/workflows/status-check.yaml@8c50ed3d1d5b4b7a113385add28e75cd229add0d # main
